/**
 * GENERATED — do not edit by hand.
 *
 * A snapshot of the pool as of the last build, used only as a fallback before
 * the backend answers and when offline. The live pool is whatever /api/config
 * returns; the BMS edits that, not this file.
 *
 * Regenerate: node scripts/gen-seed.mjs <frontend-repo>
 */
export const SEED = {
  "words": [
    "sky",
    "star",
    "moon",
    "wind",
    "rain",
    "snow",
    "fire",
    "rock",
    "stone",
    "dirt",
    "dust",
    "sand",
    "wave",
    "lake",
    "pond",
    "mud",
    "cloud",
    "gold",
    "tree",
    "leaf",
    "root",
    "wood",
    "seed",
    "bird",
    "fish",
    "frog",
    "lion",
    "bear",
    "wolf",
    "deer",
    "duck",
    "crow",
    "swan",
    "crab",
    "worm",
    "bug",
    "ant",
    "bee",
    "cat",
    "dog",
    "door",
    "wall",
    "roof",
    "desk",
    "chair",
    "bed",
    "book",
    "pen",
    "cup",
    "bowl",
    "dish",
    "fork",
    "spoon",
    "knife",
    "hat",
    "coat",
    "shoe",
    "bag",
    "ring",
    "coin",
    "bell",
    "rope",
    "hand",
    "foot",
    "face",
    "head",
    "arm",
    "leg",
    "bone",
    "skin",
    "hair",
    "mind",
    "team",
    "king",
    "big",
    "tall",
    "wide",
    "deep",
    "long",
    "fast",
    "slow",
    "loud",
    "soft",
    "hard",
    "sharp",
    "flat",
    "dark",
    "bright",
    "cold",
    "warm",
    "hot",
    "dry",
    "wet",
    "clean",
    "dirty",
    "heavy",
    "light",
    "sweet",
    "sour",
    "wild"
  ],
  "emoji": {
    "sky": "🌌",
    "star": "⭐",
    "moon": "🌙",
    "wind": "🌬️",
    "rain": "🌧️",
    "snow": "❄️",
    "fire": "🔥",
    "rock": "🪨",
    "stone": "🗿",
    "dirt": "🟤",
    "dust": "💨",
    "sand": "🏖️",
    "wave": "🌊",
    "lake": "🏞️",
    "pond": "💧",
    "mud": "🟫",
    "cloud": "☁️",
    "gold": "🥇",
    "tree": "🌳",
    "leaf": "🍃",
    "root": "🪴",
    "wood": "🪵",
    "seed": "🌱",
    "bird": "🐦",
    "fish": "🐟",
    "frog": "🐸",
    "lion": "🦁",
    "bear": "🐻",
    "wolf": "🐺",
    "deer": "🦌",
    "duck": "🦆",
    "crow": "🐦‍⬛",
    "swan": "🦢",
    "crab": "🦀",
    "worm": "🪱",
    "bug": "🐛",
    "ant": "🐜",
    "bee": "🐝",
    "cat": "🐱",
    "dog": "🐶",
    "door": "🚪",
    "wall": "🧱",
    "roof": "🏠",
    "desk": "🗂️",
    "chair": "🪑",
    "bed": "🛏️",
    "book": "📕",
    "pen": "🖊️",
    "cup": "☕",
    "bowl": "🥣",
    "dish": "🍽️",
    "fork": "🍴",
    "spoon": "🥄",
    "knife": "🔪",
    "hat": "🎩",
    "coat": "🧥",
    "shoe": "👟",
    "bag": "👜",
    "ring": "💍",
    "coin": "🪙",
    "bell": "🔔",
    "rope": "🪢",
    "hand": "✋",
    "foot": "🦶",
    "face": "😀",
    "head": "👤",
    "arm": "💪",
    "leg": "🦵",
    "bone": "🦴",
    "skin": "🧴",
    "hair": "💇",
    "mind": "🧠",
    "team": "👥",
    "king": "👑",
    "big": "🐘",
    "tall": "🦒",
    "wide": "↔️",
    "deep": "🕳️",
    "long": "📏",
    "fast": "⚡",
    "slow": "🐌",
    "loud": "📢",
    "soft": "🧸",
    "hard": "💎",
    "sharp": "🔺",
    "flat": "⬜",
    "dark": "🌑",
    "bright": "🔆",
    "cold": "🧊",
    "warm": "🌤️",
    "hot": "🌡️",
    "dry": "🏜️",
    "wet": "💦",
    "clean": "🧼",
    "dirty": "🗑️",
    "heavy": "🏋️",
    "light": "🪶",
    "sweet": "🍬",
    "sour": "🍋",
    "wild": "🌿"
  },
  "tiers": {
    "1": {
      "wordCount": 1,
      "key": "premium",
      "label": "Premium",
      "combinations": 100,
      "buyoutCents": 100000,
      "purchasePath": "DIRECT",
      "holdMs": 86400000,
      "holdLabel": "1 day"
    },
    "2": {
      "wordCount": 2,
      "key": "standard",
      "label": "Standard",
      "combinations": 10000,
      "buyoutCents": 10000,
      "purchasePath": "DIRECT",
      "holdMs": 604800000,
      "holdLabel": "7 days"
    },
    "3": {
      "wordCount": 3,
      "key": "basic",
      "label": "Basic",
      "combinations": 1000000,
      "buyoutCents": 1000,
      "purchasePath": "DIRECT",
      "holdMs": 1296000000,
      "holdLabel": "15 days"
    },
    "4": {
      "wordCount": 4,
      "key": "entry",
      "label": "Entry",
      "combinations": 100000000,
      "buyoutCents": 100,
      "purchasePath": "DIRECT",
      "holdMs": 2592000000,
      "holdLabel": "30 days"
    }
  },
  "maxWords": 4,
  "categories": {
    "nature": [
      "sky",
      "star",
      "moon",
      "wind",
      "rain",
      "snow",
      "fire",
      "rock",
      "stone",
      "dirt",
      "dust",
      "sand",
      "wave",
      "lake",
      "pond",
      "mud",
      "cloud",
      "gold"
    ],
    "life": [
      "tree",
      "leaf",
      "root",
      "wood",
      "seed",
      "bird",
      "fish",
      "frog",
      "lion",
      "bear",
      "wolf",
      "deer",
      "duck",
      "crow",
      "swan",
      "crab",
      "worm",
      "bug",
      "ant",
      "bee",
      "cat",
      "dog"
    ],
    "objects": [
      "door",
      "wall",
      "roof",
      "desk",
      "chair",
      "bed",
      "book",
      "pen",
      "cup",
      "bowl",
      "dish",
      "fork",
      "spoon",
      "knife",
      "hat",
      "coat",
      "shoe",
      "bag",
      "ring",
      "coin",
      "bell",
      "rope"
    ],
    "body": [
      "hand",
      "foot",
      "face",
      "head",
      "arm",
      "leg",
      "bone",
      "skin",
      "hair",
      "mind",
      "team",
      "king"
    ],
    "descriptors": [
      "big",
      "tall",
      "wide",
      "deep",
      "long",
      "fast",
      "slow",
      "loud",
      "soft",
      "hard",
      "sharp",
      "flat",
      "dark",
      "bright",
      "cold",
      "warm",
      "hot",
      "dry",
      "wet",
      "clean",
      "dirty",
      "heavy",
      "light",
      "sweet",
      "sour",
      "wild"
    ]
  }
};
